# Generated by Django 3.2.5 on 2021-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
